services:
  user-service:
    build: ./services/user_service
    ports:
      - "8001:8000"
    volumes:
      - ./data/databases:/data/databases
    environment:
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  product-service:
    build: ./services/product_service
    ports:
      - "8002:8000"
    volumes:
      - ./data/databases:/data/databases

  order-service:
    build: ./services/order_service
    ports:
      - "8003:8000"
    volumes:
      - ./data/databases:/data/databases

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data/databases:/data/databases
    environment:
      - PYTHONUNBUFFERED=1
      # Add these environment variables for Streamlit
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_BASE_URL_PATH=""
      - STREAMLIT_SERVER_ENABLE_CORS=false
    depends_on:
      - user-service
      - product-service
      - order-service